# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master  # Only trigger the pipeline for the main branch

pr:
  branches:
    include:
      - master  # Only trigger the pipeline for pull requests targeting the main branch

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: New Manifest for tool
  inputs:
    command: custom
    custom: 'new '
    arguments: tool-manifest

- task: DotNetCoreCLI@2
  displayName: Install EF Tool
  inputs:
    command: custom
    custom: 'tool '
    arguments: install dotnet-ef

- script: dotnet build src/AssistenciaSocial.PontuaCasos.WebApp/AssistenciaSocial.PontuaCasos.WebApp.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: DotNetCoreCLI@2
  displayName: Create SQL Scripts
  inputs:
    command: custom
    custom: 'ef '
    arguments: migrations script --output $(Build.SourcesDirectory)\pontuacasos.sql --idempotent --project src/AssistenciaSocial.PontuaCasos.WebApp/AssistenciaSocial.PontuaCasos.WebApp.csproj

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(fbb97c5c-09ae-4eb5-98e3-c4cfe9b5b4e6)'
    appType: 'webAppLinux'
    appName: 'indicadoresderisco'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: SqlDacpacDeploymentOnMachineGroup@0
  inputs:
    TaskType: 'sqlQuery'
    SqlFile: '$(Build.SourcesDirectory)\pontuacasos.sql'
    ServerName: 'pontuacasos.mssql.somee.com'
    DatabaseName: 'pontuacasos'
    AuthScheme: 'sqlServerAuthentication'
    SqlUsername: $(DatabaseUser)
    SqlPassword: $(DatabasePassword)