// <auto-generated />
using System;
using AssistenciaSocial.PontuaCasos.WebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssistenciaSocial.PontuaCasos.WebApp.Migrations
{
    [DbContext(typeof(PontuaCasosContext))]
    [Migration("20220815202425_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AssistenciaSocial.PontuaCasos.WebApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Multiplo")
                        .HasColumnType("bit");

                    b.Property<int>("OrganizacaoId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("AssistenciaSocial.PontuaCasos.WebApp.Models.Organizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("ModificadoPorId");

                    b.ToTable("Organizacoes");
                });

            modelBuilder.Entity("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MembrosOrganizacao", b =>
                {
                    b.Property<int>("OrganizacaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("OrganizacaoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MembrosOrganizacao");
                });

            modelBuilder.Entity("AssistenciaSocial.PontuaCasos.WebApp.Models.Item", b =>
                {
                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Item", null)
                        .WithMany("Itens")
                        .HasForeignKey("ItemId");

                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("ModificadoPor");

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("AssistenciaSocial.PontuaCasos.WebApp.Models.Organizacao", b =>
                {
                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", b =>
                {
                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId");

                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId");

                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Organizacao", null)
                        .WithMany("Administradores")
                        .HasForeignKey("OrganizacaoId");

                    b.Navigation("CriadoPor");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("MembrosOrganizacao", b =>
                {
                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MembrosOrganizacao_Organizacoes_OrganizacaoId");

                    b.HasOne("AssistenciaSocial.PontuaCasos.WebApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MembrosOrganizacao_Usuarios_UsuarioId");
                });

            modelBuilder.Entity("AssistenciaSocial.PontuaCasos.WebApp.Models.Item", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("AssistenciaSocial.PontuaCasos.WebApp.Models.Organizacao", b =>
                {
                    b.Navigation("Administradores");
                });
#pragma warning restore 612, 618
        }
    }
}
